language: go

notifications:
    email: false

sudo: required

go:
  - 1.9.2

before_install:
    # - set -ex
    # - VENDORED_PATH=vendor/libgit2
    # - cd $VENDORED_PATH && mkdir -p install/lib && mkdir -p build && cd build && cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX=../install .. && cmake --build .
    - sudo apt-get install libgit2-dev
    - sudo apt-get install libgit2
    
install:
    - cd $HOME/gopath/src/github.com/haasdo95/numb
    # - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/gopath/src/github.com/haasdo95/numb/vendor/libgit2:$HOME/gopath/src/github.com/haasdo95/numb/vendor/libgit2/build
    # - export PATH=$PATH:$HOME/gopath/src/github.com/haasdo95/numb/vendor/libgit2/install:$HOME/gopath/src/github.com/haasdo95/numb/vendor/libgit2/install/lib
    - go get -v -u -t github.com/haasdo95/numb

script:
  - echo "script"
