language: go

notifications:
    email: false

go:
  - 1.9.2

before_install:
    - wget "https://github.com/libgit2/libgit2/archive/v0.26.0.tar.gz"
    - tar -xf v0.26.0.tar.gz
    - ls
    # - cd v0.26.0
    # - mkdir build && cd build
    # - cmake ..
    # - cmake --build .
    # - cd ..

script:
  - echo "script"
