language: go

notifications:
    email: false

sudo: required

go:
  - 1.9.2

before_install:
    - go get -d github.com/libgit2/git2go
    - cd $GOPATH/src/github.com/libgit2/git2go
    - git submodule update --init
    - make install-static
    - cd $HOME/gopath/src/github.com/nasyxx/numb

script:
  - echo "script"
